### ISSUE TITLE
Add more resample unit tests

### ISSUE THREAD

**Issue by dkirkby** [dkirkby/speclite#1]
The resample module is currently the only one with less than 100% coverage.  This issue is to add additional unit tests to `tests/test_resample.py` to cover the lines flagged in [this coverage report](https://coveralls.io/builds/3229522/source?filename=speclite%2Fresample.py).

**Comment by dcunning11235** [comment]
Added additional tests in https://github.com/dkirkby/speclite/tree/resample_units.  Will review later:  it should be at 100% coverage but it is still showing a few exceptions/tests not covered.

**Comment by dcunning11235** [comment]
@dkirkby At 100% coverage now.  Travis build for the push done, but a second (I think for the pull) is still running.  Back after class.
