### ISSUE TITLE
Add more filter responses

### ISSUE THREAD

**Issue by dkirkby** [dkirkby/speclite#11]
@moustakas has requested MzLS-z and Bok-g,r for DESI work.  This issue is to gather the data and include it in this package.  Are there any other filters we need soon?

**Comment by moustakas** [comment]
I have a low-priority need for the CFHTLS/Megaprime ugriz filter curves.  Peter Capak curates the best ones I'm aware of:
http://www.astro.caltech.edu/~capak/filters/index.html

**Comment by dkirkby** [comment]
Do you want the new (2015) filters, the older SAGEM ones, or both?  More info [here](http://www.cfht.hawaii.edu/Instruments/Imaging/MegaPrime/specsinformation.html).

**Comment by moustakas** [comment]
The older ones, i.e., the CFHTLS-epoch filters.  Thanks.

**Comment by dkirkby** [comment]
LSST filters are included in #19

**Comment by moustakas** [comment]
Any progress on tracking down the BASS and MzLS filter curves? With the inclusion of the first round of MzLS and BASS photometry in the Legacy Survey DR3, it would be great to be able to synthesize photometry in the "northern" filters.  Maybe you can remind me where we  left off and let me know what I can do to help track the curves down.

**Comment by dkirkby** [comment]
@moustakas Can you let me know when you actually need this so I can prioritize?

**Comment by moustakas** [comment]
This isn't pressing at all, it was just on my mind.  But I'll let you know when/if this moves to the critical path!

**Comment by moustakas** [comment]
Information about the BASS filters is here (thanks to Hu!):
http://batc.bao.ac.cn/BASS/doku.php?id=datarelease:telescope_and_instrument:home#filters

The direct links to the g- and r-band filters are:  
http://batc.bao.ac.cn/BASS/lib/exe/fetch.php?media=datarelease:telescope_and_instrument:bass-g.txt
http://batc.bao.ac.cn/BASS/lib/exe/fetch.php?media=datarelease:telescope_and_instrument:bass-r.txt

The MzLS z-band filter is attached to this message.  This was attached in an email sent by Arjun Dey to @decam-chatter on 2017 June 21 and "includes telescope + corrector + camera + atmosphere at airmass=1.0":
[kpzdccdcorr3.txt](https://github.com/dkirkby/speclite/files/1094984/kpzdccdcorr3.txt)

**Comment by sbailey** [comment]
@dkirkby or others.  We will need the MzLS-z and Bok-g,r filters to wrap this up for DESI.  Could we add these by early September to include in the next DESI software release?  For now flux calibration code is still falling back to DECam filters for everything.

**Comment by moustakas** [comment]
Here are the latest set of filter curves I'm aware of, courtesy @schlafly:
https://desi.lbl.gov/trac/attachment/wiki/ImagingStandardBandpass
