### ISSUE TITLE
Recipe in conda-forge

### ISSUE THREAD

**Issue by giacomov** [dkirkby/speclite#35]
Hi,
I just submitted a pull request to the `conda-forge` organization containing a recipe for `speclite`:

[4598](https://github.com/conda-forge/staged-recipes/pull/4598)

I hope this is welcome (if not, of course, I can delete the pull request).

I'd also add @dkirkby among the maintainer of the recipe, so you can keep an eye on it and modify it if you think it is necessary. Is it ok?

Thank you for your nice work!

**Comment by dkirkby** [comment]
Thanks @giacomov!  It doesn't look like you need any changes here, but let me know otherwise.

**Comment by dkirkby** [comment]
Closing since this was merged into conda-forge Dec 2017.
